main: mudrock.permadeathPlugin
name: permadeath
version: 0.4.3
commands:
  sethome:
    description: "Sets your home"
  home:
    description: "Teleports you to your home"
  back:
    description: "Returns you to the last place you used /home from"
  tpa:
    description: "Send a request to teleport to someone"
  tpaccept:
    description: "Accept a teleportation request"
  tpdeny:
    description: "Deny a teleportation request"